(declare-const x1 Int)
(declare-const x2 Int)
(declare-const x2 Int)
(declare-const y2 Int)
(assert (>= x1 1))
(assert (>= x2 1))
(assert (>= x2 1))
(assert (>= y2 1))
(assert (or
(<= 1 0)
(<= (- (+ 12 x2) y2) 0)
))
(check-sat)
(get-model)
