[tool.poetry]
name = "test-parser-client"
version = "0.1.0"
description = ""
authors = ["RelictRLCT <pigift@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
